resume
fd1-53-17/DashaShaknova pull request #2
Opened 2017-10-30 08:35 UTC by DashaShaknova

please preview

2017-11-01 04:07 UTC, antonkulakov-it requested changes

2017-11-01 04:07 UTC, antonkulakov-it commented on resume/index.html
> +<img>
уже если вставляете img, вставляйте и src
да и вообще, где doctype, head, body?

2017-11-01 07:33 UTC, DashaShaknova commented
please preview

2017-11-03 03:59 UTC, antonkulakov-it approved these changes

2017-11-03 03:59 UTC, merged